### ISSUE TITLE
Submit OMI Request for Participation

### ISSUE THREAD

**Issue by mrmetaverse** [metaversityfoundation/metaversity#10]
If we would like to gain more support from the broader OMI audience, we can submit a request for participation via the OMI issues templates. This will inform the group that Metaversity exists, and how to get involved. 

https://github.com/omigroup/omigroup/issues/new/choose

**Comment by mrmetaverse** [comment]
Today during our weekly meeting we discussed what we would submit for our call for participation. I suggest you paste our readme content as the announcement, and add a clear request to the submission. Are we looking for more people to join metaversity and get involved in any capacity? Or are we asking for something more specific such as help crafting a webpage with tutorials? At what capacity do we want support? We still intend this to be an open community? 

# Metaversity Project Readme Barebones

[![hackmd-github-sync-badge](https://hackmd.io/dLAAQ53zQoeaoA3RYt5D3w/badge)](https://hackmd.io/dLAAQ53zQoeaoA3RYt5D3w)

###### tags: `metaversity`

- [OMI Github Strategy](/msSrKU3NQv2QO8_aU5IhHQ)

## About

### Who is involved in making this happen? 

- A wide variety of people, with a wide range of Knowledge, Skills, Abilities, and Interests. 
- We hope multiple orgs are part of this creation, as multiple orgs have something like this on their backlogs and roadmaps, and the entire metaverse benefits when we increase the number of creators. 

## :bulb: Why are we here? 

>"I wanted to take all of my bookmarks that helped me become a webxr dev, and create a wiki that would help others" - Liam

We want to organically create value by helping others become Metaverse creators and contributors. We want to find creative ways to sustain ourselves. We want to create incentive structures that align with peoples values. 

People need something that keeps them focused, and moving forward on their mission to get involved with the Metaverse. It can be easy to run into a roadblock, and get deflated or distracted. We want to make achieving the goal of becoming or improving as a Metaverse creator more attainable. We want to create incentive structures that align with peoples values. 

Furthermore, we should strive to deliver this message with minimal fluff or bullshit. The goal should be to enable folks to discover solutions and make effective choices, using _inclusive language_. 

Eventually we will have more options for metaverse contributors. Beyond developers, there will be metaverse designers, metaverse modelers, and even metaverse entertainers. Shops, services, SaaS. 

>_The metaverse is the vehicle by which we all wake up to the game we are already playing._ - gheric

## :woman: Who are we serving? 

- People building the Metaverse 
- People who want to become Metaverse developers 
- People who want to create Metaverse products
- People who want to share their knowledge with others 
- We are indirectly helping other groups in the Metaverse seeking future hires, by effectively manufacturing metaverse talent. 

## :dart: Goals: What do we hope to accomplish? (TBD)

### Objective I: Increase the number of Metaverse contributors and creators. 
### Objective II: Organically create sustainable value
### Objective III: Launch first curriculums* 
KR: Craft 3 journey maps of people becoming metaverse creators
KR: Establish curriculum for each archetype.

**Comment by mrmetaverse** [comment]
Moved the submission. The team can review by 11:59PM EDT tomorrow, and I can submit on behalf of metaversity, or we can review this again next Monday at 5pm EDT.

**Comment by shawwwwwwww** [comment]
(It looks good to me)

**Comment by mrmetaverse** [comment]
Thank you friend ☺️
